name: Deploy to AWS Lambda

on:
  push:
    branches:
      - main  # Trigger the workflow when code is pushed to the main branch
# 
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # This step checks out your code into the GitHub Actions runner

      - name: Create Zip
        run: |
          if [ -f function.zip ]; then
            rm function.zip
          fi
          zip -r function.zip src/etl-lambda/extract_transform_lambda/*

      # - name: Create Zip
      #   run: |
      #     cd src/etl-lambda/extract_transform_lambda
      #     ls -l   # List the files in the current directory for debugging
      #     pwd     # Print the current directory for debugging
      #     if [ -f function.zip ]; then
      #       rm function.zip
      #     fi
      #     zip -r function.zip * -x "*/\.*"


                          
      - name: Deploy to AWS Lambda
        uses: appleboy/lambda-action@v0.0.2  # Use a pre-built GitHub Action for deploying to Lambda
        with:
          aws_access_key_id: ${{ secrets.ACCESS_KEY }}  
          aws_secret_access_key: ${{ secrets.SECRET_ACCESS_KEY }}  
          aws_region: eu-west-2  # Use aws_region instead of region
          function_name: GHActionTest  
          zip_file: function.zip  # Specify the path to the ZIP file or directory containing your Lambda function code
